# Generated by Django 3.2.14 on 2022-11-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('accuracy', models.FloatField(max_length=255)),
            ],
        ),
    ]
