# Generated by Django 4.1.3 on 2022-12-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spamham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('our_prediction', models.CharField(max_length=255)),
                ('your_prediction', models.CharField(choices=[('SPAM', 'SPAM'), ('HAM', 'HAM')], max_length=50)),
            ],
        ),
    ]
